### ISSUE TITLE
Start postgres

### ISSUE THREAD

**Issue by ksuderman** [lappsgrid-incubator/service-manager-installation#6]
The setup.sh script needs to start Postgres before attempting to create the database, user role etc.

After starting postgres the script will also have to wait until the postgres service is available before proceeding.

@keighrim see how this is done on RedHat/CentOS and I will work on Ubuntu

**Comment by keighrim** [comment]
I guess starting up psql (and make it run when the system starts, if necessary) needs to be done from [`install-postgres.sh`](https://github.com/lappsgrid-incubator/jetstream-scripts/blob/master/install-postgres.sh) file. 
@ksuderman How did you do this for ubuntu? Within `setup.sh` script?

**Comment by ksuderman** [comment]
Yes the install-postgres.sh script is likely a better place to ensure Postgres always starts.  On Ubuntu the Postgres installer installs the startup script /etc/init.d/postgresql and configures the service to start when the system starts.  However, the installer does not actually start Postgres so I've added the lines

```bash
service postgresql start
until pg_isready ; do 
	echo "Waiting for PostgreSQL service to start"
	sleep 2
done
```

**Comment by keighrim** [comment]
Created https://github.com/lappsgrid-incubator/jetstream-scripts/pull/14

**Comment by keighrim** [comment]
Closed by lappsgrid-incubator/jetstream-scripts#14
